drop table tb_user cascade;

create table tb_user(
   user_sq        integer generated by default as identity,
   user_id         varchar(20) not null,
   user_pw       varchar(20) not null,
   user_nm       varchar(20) not null,
   user_st         varchar(1) not null
);