DROP TABLE TB_USER CASCADE;

CREATE TABLE TB_USER(
   USER_SQ       INT AUTO_INCREMENT PRIMARY KEY,
   USER_ID       VARCHAR(20) NOT NULL,
   USER_PW       VARCHAR(60) NOT NULL,
   USER_NM       VARCHAR(20) NOT NULL,
   USER_ST       VARCHAR(1) NOT NULL CHECK(USER_ST IN ('Y', 'N'))
);